server:
  address: 127.0.0.1
  port: 8088

spring:
  datasource:
    url: jdbc:sqlite:${user.home}/.zerowipe/zerowipe.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

zerowipe:
  allow-live-mode: false
